server:
  port: 8888
#Congiguration for the database
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/elearning_db
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
file_storage:
  image_location: "filestorage/images/"
  client_path: "/images/**"
springdoc:
  swagger-ui:
    path: /api

